<?php
/* 	
 		Author  						: $Author: rvv $
 		Laatste aanpassing	: $Date: 2008/09/26 07:34:44 $
 		File Versie					: $Revision: 1.8 $
 				
*/

class CRM_naw_cf extends Table
{
  /*
  * Object vars
  */
  
  var $data = array();
  var $JaNee = Array("J"=>"Ja","N"=>"Nee");
  /*
  * Constructor
  */
  function CRM_naw_cf()
  {
    $this->defineData();
    $this->setDefaults();
    $this->set($this->data['identity'],0);
  }

	function addField($name, $properties)
	{
		$this->data['fields'][$name] = $properties;
	}

	/*
	 * Veldvalidatie
	 */
	function validate()
	{

		$valid = ($this->error==false)?true:false;
		return $valid;
	}
	
	/*
	 * Toegangscontrole
	 */
	function checkAccess($type)
	{
		if($_SESSION['usersession']['superuser'])
		  return true;
		else 
		{
		  switch ($type) 
		  {
		    case "edit":
          return GetCRMAccess(1);
          break;
        case "delete":
          return false;
//          return GetCRMAccess(2);
          break;
        default:
          return false;
          break;
      }
		}  

	}
	
	/*
  * Table definition
  */
  function defineData()
  {
    $this->data['table']  = "CRM_naw_cf";
    $this->data['identity'] = "id";

		$this->addField('id',
													array("description"=>"id",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"bigint",
													"form_type"=>"text",
													"form_size"=>"20",
													"form_visible"=>false,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('rel_id',
													array("description"=>"rel_id",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"bigint",
													"form_type"=>"text",
													"form_size"=>"20",
													"form_visible"=>false,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

/*
  Onderstaande velden zijn per 27 nov 2007 verhuisd naar CRM_naw
  tzt deze velden verwijderen
*/																			
													
		$this->addField('verzendAdres',
													array("description"=>"verzendAdres",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"tinytext",
													"form_type"=>"text",
													"form_size"=>"60",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('verzendPc',
													array("description"=>"verzendPc",
													"default_value"=>"",
													"db_size"=>"17",
													"db_type"=>"varchar",
													"form_type"=>"text",
													"form_size"=>"17",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('verzendPlaats',
													array("description"=>"verzendPlaats",
													"default_value"=>"",
													"db_size"=>"30",
													"db_type"=>"varchar",
													"form_type"=>"text",
													"form_size"=>"30",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('verzendLand',
													array("description"=>"verzendLand",
													"default_value"=>"",
													"db_size"=>"25",
													"db_type"=>"varchar",
													"form_type"=>"text",
													"form_size"=>"25",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));
    $this->addField('verzendAanhef',
													array("description"=>"verzendAanhef",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"tinytext",
													"form_type"=>"text",
													"form_size"=>"60",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));							
/*
  einde verhuisde velden
*/																			

		$this->addField('custodian',
													array("description"=>"Custodian",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textaera",
													"form_size"=>"60",
													"form_rows"=>"2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));
													
    $this->addField('custodianRekeningNr',
													array("description"=>"Rekening nummer(s)",
													"default_value"=>"",
													"db_size"=>"40",
													"db_type"=>"varchar",
													"form_type"=>"text",
													"form_size"=>"40",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));													

		$this->addField('custodianAfwijkendeAfspraak',
													array("description"=>"Afwijkende afspraak",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textaera",
													"form_size"=>"60",
													"form_rows"=>"2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));
													
    $this->addField('verzendFreq',
													array("description"=>"Verzend freq rapportage",
													"default_value"=>"",
													"db_size"=>"40",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_size"=>"40",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));														

		$this->addField('kvkInDossier',
													array("description"=>"kvkInDossier",
													"default_value"=>"",
													"db_size"=>"4",
													"db_type"=>"tinyint",
													"form_type"=>"checkbox",
													"form_size"=>"4",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('statutenInDossier',
													array("description"=>"statutenInDossier",
													"default_value"=>"",
													"db_size"=>"4",
													"db_type"=>"tinyint",
													"form_type"=>"checkbox",
													"form_size"=>"4",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('rekeningActiefSinds',
													array("description"=>"rekeningActiefSinds",
													"default_value"=>"",
													"db_size"=>"0",
													"db_type"=>"date",
													"form_type"=>"calendar",
													"form_size"=>"0",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('tripartieteInDossier',
													array("description"=>"tripartieteInDossier",
													"default_value"=>"",
													"db_size"=>"4",
													"db_type"=>"tinyint",
													"form_type"=>"checkbox",
													"form_size"=>"4",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('tripartieteDatum',
													array("description"=>"tripartieteDatum",
													"default_value"=>"",
													"db_size"=>"0",
													"db_type"=>"date",
													"form_type"=>"calendar",
													"form_size"=>"0",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('vermogenbeheerOvereenkomstInDossier',
													array("description"=>"vermogenbeheerOvereenkomstInDossier",
													"default_value"=>"",
													"db_size"=>"4",
													"db_type"=>"tinyint",
													"form_type"=>"checkbox",
													"form_size"=>"4",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('vermogenbeheerOvereenkomstDatum',
													array("description"=>"vermogenbeheerOvereenkomstDatum",
													"default_value"=>"",
													"db_size"=>"0",
													"db_type"=>"date",
													"form_type"=>"calendar",
													"form_size"=>"0",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('kinderen',
													array("description"=>"kinderen",
													"default_value"=>"",
													"db_size"=>"4",
													"db_type"=>"tinyint",
													"form_type"=>"text",
													"form_size"=>"4",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('inkomenSoort',
													array("description"=>"inkomenSoort",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_select_option_notempty" =>true,
													"form_size"=>"20",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('inkomenIndicatie',
													array("description"=>"inkomenIndicatie",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('vermogenOnroerendGoed',
													array("description"=>"vermogenOnroerendGoed",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('vermogenHypotheek',
													array("description"=>"vermogenHypotheek",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('vermogenOverigVermogen',
													array("description"=>"vermogenOverigVermogen",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('vermogenOverigSchuld',
													array("description"=>"vermogenOverigSchuld",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('vermogenTotaalBelegbaar',
													array("description"=>"vermogenTotaalBelegbaar",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('vermogenBelegdViaDC',
													array("description"=>"vermogenBelegdViaDC",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('vermogenHerkomst',
													array("description"=>"vermogenHerkomst",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textaera",
													"form_size"=>"60",
													"form_rows"=>"2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('vermogenVerplichtingen',
													array("description"=>"vermogenVerplichtingen",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textaera",
													"form_size"=>"60",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringBelegtSinds',
													array("description"=>"ervaringBelegtSinds",
													"default_value"=>"",
													"db_size"=>"0",
													"db_type"=>"date",
													"form_type"=>"calendar",
													"form_size"=>"0",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringBelegtInEigenbeheer',
													array("description"=>"Eigen beheer",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_size"=>"20",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringBelegtInVermogensadvies',
													array("description"=>"vermogensadvies",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_size"=>"20",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringBelegtInProducten',
													array("description"=>"producten",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_size"=>"20",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringMetVastrentende',
													array("description"=>"Vastrentende waarden",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_size"=>"20",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringMetVastrentendeDatum',
													array("description"=>"ervaringMetVastrentendeDatum",
													"default_value"=>"",
													"db_size"=>"0",
													"db_type"=>"date",
													"form_type"=>"calendar",
													"form_size"=>"0",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringMetBeleggingsFondsen',
													array("description"=>"Beleggingsfondsen",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_size"=>"20",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringMetBeleggingsFondsenDatum',
													array("description"=>"ervaringMetBeleggingsFondsenDatum",
													"default_value"=>"",
													"db_size"=>"0",
													"db_type"=>"date",
													"form_type"=>"calendar",
													"form_size"=>"0",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringMetIndividueleAandelen',
													array("description"=>"Individuele aandelen",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_size"=>"20",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringMetIndividueleAandelenDatum',
													array("description"=>"ervaringMetIndividueleAandelenDatum",
													"default_value"=>"",
													"db_size"=>"0",
													"db_type"=>"date",
													"form_type"=>"calendar",
													"form_size"=>"0",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringMetOpties',
													array("description"=>"Opties",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_size"=>"20",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringMetOptiesDatum',
													array("description"=>"ervaringMetOptiesDatum",
													"default_value"=>"",
													"db_size"=>"0",
													"db_type"=>"date",
													"form_type"=>"calendar",
													"form_size"=>"0",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringMetFutures',
													array("description"=>"Futures",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_size"=>"20",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringMetFuturesDatum',
													array("description"=>"ervaringMetFuturesDatum",
													"default_value"=>"",
													"db_size"=>"0",
													"db_type"=>"date",
													"form_type"=>"calendar",
													"form_size"=>"0",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

			$this->addField('ervaringMetGestructureerdeProducten',
													array("description"=>"Gestructureerde producten",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_size"=>"20",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('ervaringMetGestructureerdeProductenDatum',
													array("description"=>"GestructureerdeProductenDatum",
													"default_value"=>"",
													"db_size"=>"0",
													"db_type"=>"date",
													"form_type"=>"calendar",
													"form_size"=>"0",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));												
													
		$this->addField('beleggingsHorizon',
													array("description"=>"Horizon",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_select_option_notempty" =>true,
													"form_size"=>"20",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('beleggingsDoelstelling',
													array("description"=>"Doelstelling",
													"default_value"=>"",
													"db_size"=>"30",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_select_option_notempty" =>true,
													"form_size"=>"30",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));
													
		$this->addField('opleidingsniveau',
													array("description"=>"Opleidingsniveau",
													"default_value"=>"",
													"db_size"=>"30",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_select_option_notempty" =>true,
													"form_size"=>"30",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));
													
		$this->addField('risicoprofielFinancieleGegevens',
													array("description"=>"Financiele gegevens",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textaera",
													"form_size"=>"60",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('risicoprofielGesprek',
													array("description"=>"Gesprek",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textaera",
													"form_size"=>"60",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('risicoprofielAfwijkendeAfspraak',
													array("description"=>"Afwijkende Afspraak",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textarea",
													"form_size"=>"60",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('provisieAfspraak',
													array("description"=>"Provisie afspraak",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textarea",
													"form_size"=>"60",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));
																										
		$this->addField('risicoprofielOverig',
													array("description"=>"Overig",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textaera",
													"form_size"=>"60",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('risicoprofiel',
													array("description"=>"risicoprofiel",
													"default_value"=>"",
													"db_size"=>"20",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_select_option_notempty" =>true,  
													"form_size"=>"20",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielAandelenBinnenland',
													array("description"=>"Aandelen binnenland",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielAandelenBuitenland',
													array("description"=>"Aandelen buitenland",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielObligatiesEuro',
													array("description"=>"Obligaties Euro's",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielObligatiesOverigeValuta',
													array("description"=>"Obligaties overige valuta",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielWarrants',
													array("description"=>"Warrants",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielOptiesKopenCalls',
													array("description"=>"Opties kopen calls",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielOptiesOngedektVerkopenCalls',
													array("description"=>"Opties ongedekt verkopen calls",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielOptiesGedektVerkopenCalls',
													array("description"=>"Opties gedekt verkopen calls",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielOptiesKopenPuts',
													array("description"=>"Opties kopen puts",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielOptiesVerkopenPuts',
													array("description"=>"Opties verkopen puts",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielTermijnFutures',
													array("description"=>"Termijnmarkten/futures",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielValutasInclOTC',
													array("description"=>"Valuta's incl.OTC-produkten",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielEdelmetalen',
													array("description"=>"Edelmetalen",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielVerleentToestemmingDebetstanden',
													array("description"=>"Verleent toestemming debetstanden",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielNietTerbeurzeBeleggingsfondsen',
													array("description"=>"Niet terbeurze beleggingsfondsen",
													"default_value"=>"",
													"db_size"=>"1",
													"db_type"=>"char",
													"form_type"=>"selectKeyed",
													"form_options"=>$this->JaNee,
													"form_select_option_notempty" =>true,
													"form_size"=>"1",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielInsiderRegeling',
													array("description"=>"Insider regeling",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textaera",
													"form_size"=>"60",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('profielOverigeBeperkingen',
													array("description"=>"Overige beperkingen",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textaera",
													"form_size"=>"60",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('huidigesamenstellingAandelen',
													array("description"=>"Aandelen",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('huidigesamenstellingObligaties',
													array("description"=>"Obligaties",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('huidigesamenstellingOverige',
													array("description"=>"Overige",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('huidigesamenstellingLiquiditeiten',
													array("description"=>"Liquiditeiten",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('huidigesamenstellingTotaal',
													array("description"=>"Totaal",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));
													
    $this->addField('inContactDoor',
													array("description"=>"In contact door",
													"default_value"=>"",
													"db_size"=>"30",
													"db_type"=>"varchar",
													"form_type"=>"select",
													"form_size"=>"30",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));														

		$this->addField('change_user',
													array("description"=>"change_user",
													"default_value"=>"",
													"db_size"=>"10",
													"db_type"=>"varchar",
													"form_type"=>"text",
													"form_size"=>"10",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('change_date',
													array("description"=>"change_date",
													"default_value"=>"",
													"db_size"=>"0",
													"db_type"=>"datetime",
													"form_type"=>"calendar",
													"form_size"=>"0",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('add_user',
													array("description"=>"add_user",
													"default_value"=>"",
													"db_size"=>"10",
													"db_type"=>"varchar",
													"form_type"=>"text",
													"form_size"=>"10",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('add_date',
													array("description"=>"add_date",
													"default_value"=>"",
													"db_size"=>"0",
													"db_type"=>"datetime",
													"form_type"=>"calendar",
													"form_size"=>"0",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));

		$this->addField('verplichtingenBelasting',
													array("description"=>"Belasting",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));

													
		$this->addField('verplichtingenAssurantien',
													array("description"=>"Assurantien",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));
													
		$this->addField('verplichtingenKrediet',
													array("description"=>"Krediet",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));
													
		$this->addField('verplichtingenAlimentatie',		
													array("description"=>"Alimentatie",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));
													
		$this->addField('verplichtingenStudieKinderen',
													array("description"=>"Studie kinderen",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));
														
		$this->addField('toekomstigErfenis',
													array("description"=>"Erfenis",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));
														
		$this->addField('toekomstigKapitaalsverz',
													array("description"=>"Kapitaalsverz.",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));
														
		$this->addField('toekomstigVerkoopZaak',
													array("description"=>"Verkoop zaak",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));
														
		$this->addField('toekomstigOptieregeling',
													array("description"=>"Optieregeling",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));
														
		$this->addField('toekomstigPensioenopbouw',
													array("description"=>"Pensioenopbouw",
													"default_value"=>"",
													"db_size"=>"10,2",
													"db_type"=>"double",
													"form_type"=>"text",
													"form_size"=>"10,2",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_format"=>"%01.2f",
													"list_align"=>"right",
													"list_search"=>false,
													"list_order"=>"true"));
													
	$this->addField('maandrapportage',
													array("description"=>"Maandrapportage",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textarea",
													"form_size"=>"60",
													"form_rows"=>"5",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));
	$this->addField('kwartaalrapportage',
													array("description"=>"Kwartaalrapportage",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textarea",
													"form_size"=>"60",
													"form_rows"=>"5",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));
	$this->addField('halfjaarrapportage',
													array("description"=>"Halfjaarrapportage",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textarea",
													"form_size"=>"60",
													"form_rows"=>"5",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));			
	$this->addField('jaarrapportage',
													array("description"=>"Jaarrapportage",
													"default_value"=>"",
													"db_size"=>"60",
													"db_type"=>"text",
													"form_type"=>"textarea",
													"form_size"=>"60",
													"form_rows"=>"5",
													"form_visible"=>true,
													"list_visible"=>true,
													"list_align"=>"left",
													"list_search"=>false,
													"list_order"=>"true"));																						
  }
}
?>