apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.service.name }}
  labels:
    run:  {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}   
    protocol: TCP 
    name: "tcp-{{ .Values.service.port }}"
  selector:
    run:  {{ .Values.service.name }}
